import { useId, useState } from "react";
import { useApp } from "../context/AppContext";
import { useToast } from "../context/ToastContext";
import type { EventKind, EventSeries, ScheduleEvent, SeriesCadence } from "../types";
import { EVENT_KIND } from "../data/constants";
import { Sheet } from "./Sheet";
import { SheetActions } from "./SheetActions";
import { ChipSelect } from "./ChipSelect";
import { PickerField } from "./PickerField";
import { useQuickCreate } from "../hooks/useQuickCreate";
import { SegmentedControl } from "./SegmentedControl";
import { domId, makeId } from "../utils/id";
import { useDirtyGuard } from "../hooks/useDirtyGuard";
import { addDays, parseISODate, todayISO } from "../utils/dates";
import { describeSeries, reshapeFuture, seriesFuture } from "../utils/series";
import { haptic } from "../lib/haptics";
import { prefersAutoFocus } from "../lib/device";

/* ── EventSheet ──
   One-off events and recurring sessions in the same sheet.

   Creating with "Repetir" ≠ Nunca makes an EventSeries; the occurrences
   (this one included) are generated by AppContext once the series row
   lands. Editing an occurrence asks how far the change should reach:

     Solo este         → patch this row, mark it detached
     Este y siguientes → end the old series the day before, start a new
                         one from here, drop the old future rows
     Toda la serie     → patch the series + every future non-detached row */

type Repeat = "never" | SeriesCadence;
type Scope = "one" | "future" | "all";

const REPEAT_ITEMS: { k: Repeat; l: string }[] = [
  { k: "never", l: "Nunca" },
  { k: "weekly", l: "Semanal" },
  { k: "biweekly", l: "Quincenal" },
  { k: "monthly", l: "Mensual" }
];
const SCOPE_ITEMS: { k: Scope; l: string }[] = [
  { k: "one", l: "Solo este" },
  { k: "future", l: "Desde este" },
  { k: "all", l: "Toda la serie" }
];
const WEEKDAYS = [
  { v: 1, l: "L" },
  { v: 2, l: "M" },
  { v: 3, l: "M" },
  { v: 4, l: "J" },
  { v: 5, l: "V" },
  { v: 6, l: "S" },
  { v: 0, l: "D" }
];

export function EventSheet({
  event,
  initialDate,
  initialKind,
  initialTitle,
  initialCourseId,
  onClose
}: {
  event: ScheduleEvent | null;
  /** Pre-fill the date when creating from a calendar day. */
  initialDate?: string;
  /** Pre-select the kind (Expos creates expos). */
  initialKind?: EventKind;
  /** Pre-fill the title (a course adds a session under its own name). */
  initialTitle?: string;
  /** Pre-link a new session to a course she takes. */
  initialCourseId?: string;
  onClose: () => void;
}) {
  const {
    addEvent,
    updateEvent,
    removeEvent,
    removeEvents,
    addSeries,
    updateSeries,
    removeSeries,
    series: allSeries,
    events,
    projects,
    contacts,
    courses,
    settings
  } = useApp();
  const { showSuccess, showToast } = useToast();
  const quick = useQuickCreate();
  const parent: EventSeries | null = event?.seriesId ? (allSeries.find((s) => s.id === event.seriesId) ?? null) : null;

  const [title, setTitle] = useState(event?.title ?? initialTitle ?? "");
  const [courseId, setCourseId] = useState(event?.courseId ?? parent?.courseId ?? initialCourseId ?? "");
  const [kind, setKind] = useState<EventKind>(event?.kind ?? initialKind ?? "class");
  const [budget, setBudget] = useState(event?.budget?.toString() ?? "");
  const [date, setDate] = useState(event?.date ?? initialDate ?? todayISO());
  const [startTime, setStartTime] = useState(event?.startTime ?? "");
  const [endTime, setEndTime] = useState(event?.endTime ?? "");
  const [location, setLocation] = useState(event?.location ?? "");
  const [projectId, setProjectId] = useState(event?.projectId ?? "");
  const [contactId, setContactId] = useState(event?.contactId ?? "");
  const [notes, setNotes] = useState(event?.notes ?? "");
  const [repeat, setRepeat] = useState<Repeat>(parent?.cadence ?? "never");
  const [weekdays, setWeekdays] = useState<number[]>(parent?.weekdays ?? []);
  const [until, setUntil] = useState(parent?.endDate ?? "");
  const [scope, setScope] = useState<Scope>("one");
  const [submitting, setSubmitting] = useState(false);

  const uid = domId(useId());
  /* `scope` is left out on purpose: it changes what Guardar does, not
     what she typed, so moving it alone loses nothing. */
  const dirty = useDirtyGuard({
    title, courseId, kind, budget, date, startTime, endTime, location,
    projectId, contactId, notes, repeat, weekdays, until
  });

  const safeClose = submitting ? null : onClose;
  const canSave = title.trim().length > 0 && date.length > 0 && (!until || until >= date);
  const projectOptions = [...projects]
    .sort((a, b) => a.title.localeCompare(b.title))
    .map((p) => ({ value: p.id, label: p.title }));
  const contactOptions = [...contacts]
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((c) => ({ value: c.id, label: c.name }));
  const courseOptions = courses
    .filter((c) => c.status === "active" || c.status === "upcoming" || c.id === courseId)
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((c) => ({ value: c.id, label: c.name }));

  const eventPatch = {
    title: title.trim(),
    kind,
    courseId: courseId || null,
    startTime: startTime || null,
    endTime: endTime || null,
    location: location.trim(),
    projectId: projectId || null,
    contactId: contactId || null,
    budget: kind === "expo" && budget ? Number(budget) : null,
    notes: notes.trim()
  };
  const seriesShape = (from: string): Omit<EventSeries, "id" | "createdAt"> => ({
    title: eventPatch.title,
    kind,
    cadence: repeat === "never" ? "weekly" : repeat,
    weekdays: repeat === "monthly" ? [] : weekdays.length ? weekdays : [parseISODate(from).getDay()],
    startTime: eventPatch.startTime,
    endTime: eventPatch.endTime,
    location: eventPatch.location,
    startDate: from,
    endDate: until || null,
    projectId: eventPatch.projectId,
    contactId: eventPatch.contactId,
    groupId: parent?.groupId ?? null,
    courseId: eventPatch.courseId,
    notes: eventPatch.notes
  });

  async function handleSave() {
    if (!canSave) return;
    setSubmitting(true);

    // ── New ──
    if (!event) {
      if (repeat === "never") {
        void addEvent({
          id: makeId(),
          createdAt: todayISO(),
          date,
          missed: false,
          seriesId: null,
          cancelled: false,
          detached: false,
          ...eventPatch
        });
        showSuccess("Evento creado");
      } else {
        // Occurrences follow once the series has landed (AppContext).
        void addSeries({ id: makeId(), createdAt: todayISO(), ...seriesShape(date) });
        showSuccess("Sesiones programadas");
      }
      haptic.success();
      onClose();
      return;
    }

    // ── Edit a one-off, or an occurrence "solo este" ──
    if (!parent || scope === "one") {
      if (parent && date !== event.date) {
        // Moving an occurrence: its original slot stays as a cancelled
        // row (so the generator doesn't refill that date) and the moved
        // session becomes a one-off of its own.
        /* Same ordering rule as the split below: the moved session is
           created first, so a rejected insert cannot leave her with the
           original slot cancelled and no session anywhere. */
        setSubmitting(true);
        const moved = await addEvent({
          id: makeId(),
          createdAt: todayISO(),
          date,
          missed: event.missed,
          seriesId: null,
          cancelled: false,
          detached: false,
          ...eventPatch
        });
        if (!moved) {
          setSubmitting(false);
          showToast("No se pudo mover la sesión. Sigue en su fecha original.", "error", { persistent: true });
          return;
        }
        await updateEvent(event.id, { cancelled: true });
        setSubmitting(false);
      } else {
        void updateEvent(event.id, { ...eventPatch, date, ...(parent ? { detached: true } : {}) });
      }
      haptic.success();
      showSuccess("Evento actualizado");
      onClose();
      return;
    }

    // ── "Toda la serie": rewrite the rule + every future non-detached row ──
    if (scope === "all") {
      const shape = seriesShape(parent.startDate);
      /* The rule is capped FIRST and awaited. Dropping the dates while a
         refused reshape reverts leaves them "missing" under the old shape,
         and the generator simply refills what she just cleared. */
      if (!(await updateSeries(parent.id, shape))) {
        setSubmitting(false);
        showToast("No se pudo actualizar la serie. Nada se cambió.", "error", { persistent: true });
        return;
      }
      const { keep, drop, patch } = reshapeFuture(parent, shape, events, todayISO());
      for (const occ of keep) void updateEvent(occ.id, patch);
      if (drop.length) void removeEvents(drop.map((e) => e.id));
      haptic.success();
      showSuccess("Serie actualizada");
      onClose();
      return;
    }

    /* ── "Este y siguientes": split the series at this occurrence ──
       Order is the safety property. These three writes used to fire
       unordered with `void` and report success unconditionally, so a
       rejected addSeries left the old series already capped and its future
       sessions already deleted — her class gone from that date on, with
       nothing left to regenerate it and a green toast saying it worked.
       Build the replacement FIRST: until it exists, nothing is destroyed. */
    setSubmitting(true);
    const future = seriesFuture(parent, events, event.date);
    const created = await addSeries({ id: makeId(), createdAt: todayISO(), ...seriesShape(date) });
    if (!created) {
      setSubmitting(false);
      showToast("No se pudo dividir la serie. Nada se cambió.", "error", { persistent: true });
      return;
    }
    // The replacement exists; retiring the old half is now safe to lose.
    await updateSeries(parent.id, { endDate: addDays(event.date, -1) });
    await removeEvents(future.map((e) => e.id));
    setSubmitting(false);
    haptic.success();
    showSuccess("Serie dividida desde esta fecha");
    onClose();
  }

  async function handleDelete() {
    if (!event) return;
    setSubmitting(true);
    let ok: boolean;
    let done: string;
    if (!parent || scope === "one") {
      // A series slot stays as a cancelled row so regeneration skips it.
      ok = parent ? await updateEvent(event.id, { cancelled: true }) : await removeEvent(event.id);
      done = "Evento eliminado";
    } else if (scope === "all") {
      ok = await removeSeries(parent.id);
      done = "Serie eliminada";
    } else {
      /* Cap the series BEFORE deleting its occurrences. The other order lets
         a rejected cap leave the sessions deleted and the rule still active,
         so the generator simply refills the dates she just cleared. */
      const future = seriesFuture(parent, events, event.date);
      ok = await updateSeries(parent.id, { endDate: addDays(event.date, -1) });
      if (ok) ok = await removeEvents(future.map((e) => e.id));
      done = "Sesiones siguientes eliminadas";
    }
    setSubmitting(false);
    if (!ok) {
      // The store already put back whatever it had removed.
      showToast("No se pudo eliminar. Nada se borró.", "error", { persistent: true });
      return;
    }
    haptic.warn();
    showSuccess(done);
    onClose();
  }

  const toggleWeekday = (v: number) => {
    haptic.tap();
    setWeekdays((list) => (list.includes(v) ? list.filter((d) => d !== v) : [...list, v]));
  };

  return (
    <Sheet
      title={event ? (parent ? "Editar sesión" : "Editar evento") : "Nuevo evento"}
      onClose={safeClose}
      dirty={dirty}
      discardText={
        event
          ? "¿Descartar los cambios? El evento se queda como estaba."
          : "¿Descartar? Este evento no se agenda."
      }
      footer={
        <SheetActions
          canSave={canSave}
          submitting={submitting}
          onSave={() => void handleSave()}
          onDelete={event ? () => void handleDelete() : undefined}
          confirmText={
            parent
              ? scope === "all"
                ? "¿Eliminar toda la serie y sus sesiones?"
                : scope === "future"
                  ? "¿Eliminar esta sesión y las siguientes?"
                  : "¿Eliminar solo esta sesión?"
              : "¿Eliminar este evento?"
          }
        />
      }
    >
      {parent && (
        <div className="money-panel money-panel--compact scope-panel" style={{ marginBottom: 14 }}>
          <div className="money-submeta">
            Parte de una serie · {describeSeries(parent)}
            {parent.endDate ? ` · hasta ${parent.endDate}` : ""}
          </div>
          <SegmentedControl
            items={SCOPE_ITEMS}
            value={scope}
            onChange={(k) => setScope(k as Scope)}
            size="sm"
            role="radiogroup"
            ariaLabel="Alcance del cambio"
          />
        </div>
      )}

      <div className="input-group">
        <label className="input-label" htmlFor="event-title">Título</label>
        <input id="event-title" className="input" value={title} onChange={(e) => setTitle(e.target.value)} autoFocus={event === null && prefersAutoFocus()} />
      </div>

      <div className="input-group">
        <span className="input-label">Tipo</span>
        <ChipSelect options={EVENT_KIND} value={kind} onChange={setKind} ariaLabel="Tipo de evento" />
      </div>

      {(kind === "class" || kind === "other") && (settings.practice.includes("studies") || courses.length > 0) && (
        <div className="input-group">
          <span className="input-label" id={`${uid}-course`}>Curso que tomas</span>
          <PickerField
            labelId={`${uid}-course`}
            title="Curso"
            options={courseOptions}
            value={courseId}
            onChange={setCourseId}
            placeholder="Ninguno"
            onCreate={(name) => quick.course(name, { startDate: date })}
            createLabel="Nuevo curso"
          />
        </div>
      )}

      <div className="input-group">
        <label className="input-label" htmlFor="event-date">{parent && scope !== "one" ? "Desde" : "Fecha"}</label>
        <input id="event-date" className="input" type="date" value={date} onChange={(e) => setDate(e.target.value)} />
      </div>

      <div className="form-row">
        <div className="input-group">
          <label className="input-label" htmlFor="event-start">Hora inicio</label>
          <input id="event-start" className="input" type="time" value={startTime} onChange={(e) => setStartTime(e.target.value)} />
        </div>
        <div className="input-group">
          <label className="input-label" htmlFor="event-end">Hora fin</label>
          <input id="event-end" className="input" type="time" value={endTime} onChange={(e) => setEndTime(e.target.value)} />
        </div>
      </div>

      {(!event || (parent && scope !== "one")) && (
        <div className="input-group">
          <span className="input-label">Repetir</span>
          <SegmentedControl
            items={REPEAT_ITEMS}
            value={repeat}
            onChange={(k) => setRepeat(k as Repeat)}
            size="sm"
            role="radiogroup"
            ariaLabel="Repetir"
          />
          {(repeat === "weekly" || repeat === "biweekly") && (
            <div className="weekday-row" style={{ marginTop: 10 }} role="group" aria-label="Días de la semana">
              {WEEKDAYS.map((d) => (
                <button
                  type="button"
                  key={d.v}
                  className="weekday-chip"
                  aria-pressed={weekdays.includes(d.v)}
                  aria-label={["domingo", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado"][d.v]}
                  onClick={() => toggleWeekday(d.v)}
                >
                  {d.l}
                </button>
              ))}
            </div>
          )}
          {repeat !== "never" && (
            <>
              <div className="input-help">
                {describeSeries({
                  cadence: repeat,
                  weekdays: repeat === "monthly" ? [] : weekdays,
                  startDate: date || todayISO(),
                  endDate: until || null
                })}
                . Angus agenda las sesiones de los próximos 3 meses y sigue agregando.
              </div>
              <div className="input-group" style={{ marginTop: 10, marginBottom: 0 }}>
                <label className="input-label" htmlFor="event-until">Hasta (opcional)</label>
                <input id="event-until" className="input" type="date" value={until} min={date} onChange={(e) => setUntil(e.target.value)} />
              </div>
            </>
          )}
        </div>
      )}

      {kind === "expo" && (
        <div className="input-group">
          <label className="input-label" htmlFor="event-budget">Presupuesto (MXN)</label>
          <div className="money-input-wrap">
            <span className="money-input-symbol">$</span>
            <input id="event-budget" className="input money-input" type="number" inputMode="decimal" value={budget} onChange={(e) => setBudget(e.target.value)} placeholder="0" />
          </div>
          <div className="input-help">Stand, transporte, impresiones. Para saber si la expo se paga sola.</div>
        </div>
      )}

      <div className="input-group">
        <label className="input-label" htmlFor="event-location">Ubicación</label>
        <input id="event-location" className="input" value={location} onChange={(e) => setLocation(e.target.value)} />
      </div>

      <div className="input-group">
        <span className="input-label" id={`${uid}-project`}>Pieza relacionada</span>
        <PickerField
          labelId={`${uid}-project`}
          title="Pieza relacionada"
          options={projectOptions}
          value={projectId}
          onChange={setProjectId}
          onCreate={(name) =>
            // The kind already says what the piece is: shown at an expo →
            // finished; a deadline → in progress and due that day.
            quick.project(
              name,
              kind === "expo"
                ? { status: "completed", contactId: contactId || null }
                : kind === "deadline"
                  ? { status: "in_progress", dueDate: date, contactId: contactId || null }
                  : { contactId: contactId || null }
            )
          }
          createLabel="Nueva pieza"
        />
      </div>

      <div className="input-group">
        <span className="input-label" id={`${uid}-contact`}>Contacto relacionado</span>
        <PickerField
          labelId={`${uid}-contact`}
          title="Contacto relacionado"
          options={contactOptions}
          value={contactId}
          onChange={setContactId}
          onCreate={(name) => quick.contact(name, kind === "expo" ? "gallery" : "other")}
          createLabel="Nuevo contacto"
        />
      </div>

      <div className="input-group">
        <label className="input-label" htmlFor="event-notes">Notas</label>
        <textarea id="event-notes" className="input" rows={3} value={notes} onChange={(e) => setNotes(e.target.value)} />
      </div>
    </Sheet>
  );
}
